package action

import (
	"encoding/yaml"
	"tool/file"
)

// genaction exports the action configuration to action.yml
//
// When the as-yet-unpublished embeding example is implemented,
// this command will become superfluous and could be replaced
// by a cue export call.
command: genaction: file.Create & {
	filename: "action.yml"
	contents: """
					# Generated by cue cmd genaction; do not edit

					\(yaml.Marshal(action))
					"""
}
