package action

import (
	"encoding/yaml"
	"path"
	"tool/file"
)

_goos: *"unix" | string @tag(os,var=os)

// genworkflows exports workflow configurations to .yml files.
//
// When the as-yet-unpublished embeding example is implemented,
// this command will become superfluous and could be replaced
// by a cue export call.
command: genworkflows: {
	for _, w in workflows {
		"\(w.filename)": file.Create & {
			_path: path.FromSlash(".github/workflows", "unix")
			filename: path.Join([_path, w.filename], _goos)
			contents: """
					# Generated by cue cmd genworkflows; do not edit

					\(yaml.Marshal(w.workflow))
					"""
		}
	}
}
